### ISSUE TITLE
System.IO.FileFormatException: File contains corrupted data - Excel file(.xlsx)

### ISSUE THREAD

**Issue by shailesh1984** [dotnet/Open-XML-SDK#1317]
**Describe the bug**
Getting "System.IO.FileFormatException: File contains corrupted data" error in SpreadsheetDocument.Open(filename, false); method for excel(.xlsx) file

Error Detail : 
System.Exception: OpenXML failed to open Pricing file | ‘System.IO.FileFormatException: File contains corrupted data.
	at MS.Internal.IO.2ip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
	at MS.Internal.IO.Zip.ZiplOEndOfCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
	at MS.Internal.IO.Zip.ZipArchive..ctor(Stream archiveStream, FileMode mode, FileAccess access, Boolean streaming, Boolean ownStream)at
MS.Internal.IO.2ip.ZipArchive.OpenOnFile(String path, FileMode mode, FileAccess access, FileShare share, Boolean streaming)
	at System.IO.Packaging.ZipPackage..ctor(String path, FileMode mode, Fileccess access, FileShare share, Boolean streaming)
	at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare, Boolean streaming)
	at DocunentFormat.OpenXnl.Packaging.OpenknlPackage-OpenCore(String path, Boolean readiiniteMode)
	at DocumentFormat.Openxnl.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable, OpenSettings openSettings)

How to fix this issue?

**Comment by ThomasBarnekow** [comment]
@shailesh1984, we need more information to help (e.g., as indicated by the template you were asked to fill in when creating this issue). Most importantly, we'd need to be able to reproduce the issue. Also, we need the version (e.g., 2.18.0, 2.19.0) of the Open XML SDK (`DocumentFormat.OpenXml` package) you are using.

As the exception message says, the "file contains corrupted data." So the file itself may be corrupt, which would not be a bug in the Open XML SDK (or any other library). Looking at the stack trace, the exception is thrown by the `FindPosition(Stream)` method of the [ZipIOEndOfCentralDirectoryBlock](https://referencesource.microsoft.com/#windowsbase/Base/MS/Internal/IO/Zip/ZipIOEndOfCentralDirectoryBlock.cs,617f9c997ea6c25d) class, which is part of the `WindowsBase` framework assembly.

Based on your information, this does not look like a bug in the Open XML SDK (this project).

**Comment by shailesh1984** [comment]
Is there any way to avoid temporary file opening in OpenXml? 
or
We need to handle it in the code itself.
ex : 
if(fileName.StartsWith("~")){ }

**Comment by ThomasBarnekow** [comment]
Your code is responsible for passing the right file names, streams, or packages to the Open XML SDK. If the data contained in a file, stream, or package is corrupt, the bug or issue is on your side and you'll have to deal with that. The Open XML SDK or other framework libraries can only handle cases where you provide invalid or corrupt data by throwing exceptions, for example.

**Comment by shailesh1984** [comment]
Thank you
