### ISSUE TITLE
Bug with Open XML SDK

### ISSUE THREAD

**Issue by cjuarezcv** [dotnet/Open-XML-SDK#1436]
**Describe the bug**
Error trying to open only certain Excel files using file.CopyToAsync(memoryStream)

Object reference not set to an instance of an object. -    at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
   at ClosedXML.Excel.XLWorkbook.Load(Stream stream)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream, LoadOptions loadOptions)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream)

**Comment by tomjebo** [comment]
@cjuarezcv did you check with ClosedXML project to see if this is an issue with XLWorkBook?

**Comment by cjuarezcv** [comment]
@tomjebo Sorry, this got put in the wrong repository.  Closing the issue.
