### ISSUE TITLE
Feature request for Open XML SDK - Exclude unsupported XML characters during file generation

### ISSUE THREAD

**Issue by tauheedul** [dotnet/Open-XML-SDK#1532]
I have encountered an scenario where a user has entered data into the database which included control characters (most likely from a 3rd party system).

Subequently when attempting to export the data to an OpenXML spreadsheet directly from the database e.g. creating a spreadsheet using a DataTable with no pre-processing, the Open XML plugin fails because of the invalid hex characters detected.

**Suggested solution**
Upon saving a datatable and while parsing each column value, detect Invalid Xml Characters and exclude them from the output file or transform them to an XML equivalent character where possible.

**The workaround**
The workaround for us is to find every field at source and exclude invalid characters being added to the database, but this isn't feasable for a large system.

The other solution is to map the data table manually parse every column while mapping the columns and exclude special characters there, but that adds additional overhead for large datasets because the table will be iterated again when OpenXML opens the dataset.

**Example error**

![image](https://github.com/dotnet/Open-XML-SDK/assets/9335220/77930566-bd6d-4511-aa47-aae3418bb631)

- Exception message

'', hexadecimal value 0x02, is an invalid character.

- Exception stacktrace

   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at DocumentFormat.OpenXml.OpenXmlLeafTextElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.Save(Stream stream)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.SaveToPart(OpenXmlPart openXmlPart)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.Save()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.TrySavePartContent(OpenXmlPart part)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.SavePartContents(Boolean save)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose(Boolean disposing)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose()
   at TestOpenXmlSpreadsheet.Helper.ExportToExcelDownload(DataSet dataSet) in C:\Users\user\Source\repos\TestOpenXmlSpreadsheet\TestOpenXmlSpreadsheet\Form1.cs:line 118
   at TestOpenXmlSpreadsheet.Form1.btnTest_Click(Object sender, EventArgs e) in C:\Users\user\Source\repos\TestOpenXmlSpreadsheet\TestOpenXmlSpreadsheet\Form1.cs:line 39
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by twsouthwick** [comment]
do you have a repro project to try locally?

My first thought is that this kind of validation probably doesn't belong here. If you are constructing the document, you can inject some validation/sanitizer methods at that level. If you have an idea of what code pattern you are hoping to enable, we can potentially add something here, but it doesn't feel right at this level.

**Comment by tauheedul** [comment]
Hello @twsouthwick I've attached my sample test project to replicate the issue manually.
[TestOpenXmlSpreadsheet.zip](https://github.com/dotnet/Open-XML-SDK/files/12868241/TestOpenXmlSpreadsheet.zip)

The issue could occur in situations you would directly query the database and return the results as a DataTable with no pre-processing. Most developers would not check the record before adding it to the sheetData as they would expect the package to handle breaking XML characters on cell.Append()

Presently, the raw text is added to the sheet data, but no exception is raised until after the application invokes the Save method.
workbookpart.Workbook.Save();

The XML error will be thrown from the OpenXML package as described.

**Comment by twsouthwick** [comment]
@tauheedul I see how it might make it easier to inject it here. I'd be open to a PR here if you're interested in contributing. My recommendation to how we may want to do it (feel free to give a different design):

- We make use of [features](./docs/Features.md) to abstract behavior away (if you're familiar with ASP.NET Core HttpContext.Features, it's a similar idea)
- Right now, I believe we create XmlWriter instances throughout the code base without a single place to do so
- Move all of those into a single location
- Plumb that through into features
- Expose an extension method that replaces the default feature with one that sanitizes things by giving it a derived XmlWriter that does sanitizing. It may be configurable for different definitions of *sanitize*, but starting off it could do some reasonable default behavior.

This means, that from an end-user (developer) perspective, the usage would be:

```csharp
var package = WordprocessingDocument.Create(....);
package.UseTextSanitization();

// use as normal
```

The key principles I can think of for this are:

- It should be pay-for-play: if someone doesn't want to incur the cost of sanitizing, they shouldn't
- Should be an orthogonal behavior to anything else going on

Happy to accept other ideas for how this should be done. If you're interested in using the plan I proposed above, feel free to submit PRs (potentially incremental so you can get used to our process) to enable that.

**Comment by tipa** [comment]
I am facing the same problem and would welcome a fix! I am currently filtering out invalid characters in my own code

**Comment by twsouthwick** [comment]
Happy to take a PR to enable any of the steps I listed above :) I don't have time currently to commit to any feature work, but happy to review/guide if someone wants to claim this one!

**Comment by twsouthwick** [comment]
Thanks @tauheedul! I'll leave this here for anyone that wants to take it on.

Note: Another example would be from [WCF](https://referencesource.microsoft.com/#mscorlib/system/security/securityelement.cs,473ffcff31aa5090) that uses a bit more performant way of doing it. It would be great to use [SearchValues](https://learn.microsoft.com/en-us/dotnet/api/system.buffers.searchvalues?view=net-8.0) for the .NET 8 build of this to optimize it even more.

**Comment by Nick-HK** [comment]
@twsouthwick 

I have a quick question before I proceed with creating a PR for the initial task. Would it be more appropriate to create the internal static class for XmlWriter under /src/common, or should it be nested under DocumentFormat.OpenXml.Framework?

This function will be required for my upcoming project, and I’m eager to make my first contribution to this issue. I look forward to your guidance and suggestions.

**Comment by twsouthwick** [comment]
Do it in the framework project. The common is mostly for poly fills to support old. Net versions. Thanks for jumping in for contributing!

**Comment by Nick-HK** [comment]
Hi team, I have revised our current creation of the XmlWriter based on the suggestion from @twsouthwick. I might properly create a XmlWriterFactory class to share the XmlWriter creation. Something like this maybe? Not sure if that's the best way to start with but feel free to comment/contirbute!

`public static class XmlWriterFactory
{
    public static XmlWriter Create(/* parameters as needed */)
    {
        // Create and return an XmlWriter instance?
    }
}
`

**Comment by twsouthwick** [comment]
That's fine to start with, but make it internal. For public consumption, I prefer to stay away from static things and use https://learn.microsoft.com/en-us/office/open-xml/general/features.

For example:

```csharp
public interface IXmlWriterFeature
{
  XmlWriter Create(XmlWriterSettings? settings = null);
}

internal static class XmlWriterExtensions
{
  public static XmlWriter CreateXmlWriter(this OpenXmlPartContainer container, XmlWriterSettings? settings = null)
    => container.Features.GetRequiredFeature<IXmlWriterFeature>().Create(settings);
```

Implementing the feature collection for OpenXmlpartcontainer with IXmlWriterFeature should allow this to light up while still being overrideable if needed.

As I mentioned above, feel free to first work on getting things extracted so that the writers are all created in the right place, then we can figure out what the public API should look like.

**Comment by twsouthwick** [comment]
Another option is to use the `OpenXmlWriterSettings` that is being introduced in https://github.com/dotnet/Open-XML-SDK/pull/1902

**Comment by lindexi** [comment]
@twsouthwick Does this will add the built-in support for https://github.com/dotnet/Open-XML-SDK/issues/1874

**Comment by twsouthwick** [comment]
We currently don't have it planned but we'll accept a PR for it
