### ISSUE TITLE
Method not found: 'DocumentFormat.OpenXml.OpenXmlElementList DocumentFormat.OpenXml.OpenXmlElement.get_ChildElements()'.

### ISSUE THREAD

**Issue by warkakw** [dotnet/Open-XML-SDK#1608]
DocumentFormat.OpenXml 3.0.0

new XLWorkbook(stream) throws this exception:

Method not found: 'DocumentFormat.OpenXml.OpenXmlElementList DocumentFormat.OpenXml.OpenXmlElement.get_ChildElements()'.

   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
   at ClosedXML.Excel.XLWorkbook.Load(Stream stream)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream, LoadOptions loadOptions)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream)

**Comment by twsouthwick** [comment]
This is a major change, so there are some breaking changes (see https://learn.microsoft.com/en-us/office/open-xml/migration/migrate-v2-to-v3) that will require dependencies to be updated to consume. It should mostly be compile time changes, but I've tried to document all of them (let me know if there are others) that may be seen.
