### ISSUE TITLE
SpredsheetDocument.Save() InvalidOperationException (Collection was modified)

### ISSUE THREAD

**Issue by SirParser** [dotnet/Open-XML-SDK#1659]
When executing SpreadsheetDocument.Save() (i.e. base class OpenXmlPackage.Save()) I'm getting the following error:
InvalidOperationException
Collection was modified; enumeration operation may not execute.
StackTrace: 
[DBG]: PS ...>> $_.Exception.InnerException.StackTrace
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at DocumentFormat.OpenXml.Features.PackageFeatureBase.UpdateCachedItems()
   at DocumentFormat.OpenXml.Packaging.Builder.SavePackageExtensions.SaveablePackage.Save()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Save()

This happens only when I'm using the library in a PowerShell script. 
While debugging in JetBrains Rider (on the same machine) it works OK.
It looks like something about the 'Cached Items' is handled differently when library is used after installing in 
'C:\Program Files\PackageManagement\NuGet\Packages', comparing to debugging it in IDE.
Has anyone encountered this issue?

Environment:
Windows Server 2016
PowerShell 5.1
IDE: JetBrains Rider 2023.3.3
DocumentFormat.OpenXml.3.0.0

**Comment by SirParser** [comment]
I stepped through PackageFeatureBase.UpdateCachedItems() in  DocumentFormat.OpenXml.Features
`    
internal abstract class PackageFeatureBase  ...
protected void UpdateCachedItems()
{
      if (this._parts == null)
        return;
      foreach (KeyValuePair<Uri, PackageFeatureBase.PackagePart> part in this._parts)
      {
        if (this.Package.PartExists(part.Key))
          part.Value.Part = this.Package.GetPart(part.Key);
        else
          this._parts.Remove(part.Key);
      }
}
`
I'm not an expert, but I thought you're not supposed to remove keys from a Dictionary while looping over it.

Anyway, my code does reach the 'Remove' part and deletes removed parts. I'm not sure if this should be happening.
I might be doing something wrong earlier, maybe those obsolete parts need to be somehow handled explicitly, not sure how though.

**Comment by AlfredHellstern** [comment]
@twsouthwick can you take a look?

**Comment by twsouthwick** [comment]
@SirParser can you provide a repro for me?

**Comment by SirParser** [comment]
Thanks @AlfredHellstern and @twsouthwick 
attached steps to reproduce the error
[Repro.zip](https://github.com/dotnet/Open-XML-SDK/files/14205875/Repro.zip)

**Comment by twsouthwick** [comment]
Oh - you're loading it manually through powershell and on an older version of powershell. You should be resolving the .net framework assemblies if you want to do as you're on Powershell 5.1

However, resolving them manually is difficult given powershell vs powershell core. We could potentially package them up as a powershell module so that things are resolved correctly. I haven't done that for a while, but I'd be open for taking a PR to enable an official powershell module that would set things up correctly.

**Comment by twsouthwick** [comment]
For more technical details, on .NET 6, enumerating over a dictionary that has had items removed is now supported. So, we special case our compilation to have a different pathway for .NET 6+ vs others: https://github.com/dotnet/Open-XML-SDK/blob/35b91d3c18fc06379b74f0980e3498f2b04c1fc8/src/DocumentFormat.OpenXml.Framework/Features/PackageFeatureBase.cs#L46-L82

**Comment by SirParser** [comment]
Hi Taylor,

I haven't had time to look into this in the last few months, but some requirement popped up recently and I ran into this issue again. This time I wanted to use an Excel template with a table and that triggered again the UpdateCachedItems() method and the "Collection was modified..." error.
I started pulling my hair out again trying to get the right versions and frameworks in place but to little avail. At least I kind of confirmed that the intended pre-NET.6 version of that method is being executed. 
Then I looked at the pre-NET.6 compiled code (and your code snippet above) and I realized that it doesn't actually address the dictionary item removal issue, because despite using an additional temp List ('unused') of keys (Uris), it still removes the OpenXmlPart within the original loop.
For this to work, the removal part using the 'unused' List has to happen outside of the original loop over '_parts'.
Can you check my quick mockup in attachment and let me know if that makes sense?
[Test.txt](https://github.com/dotnet/Open-XML-SDK/files/15293243/Test.txt)
(it has to run in a .NET Framework 4.5+ Console App)

Regards, PM

**Comment by SirParser** [comment]
Here's the proposed change:
```csharp
	protected void UpdateCachedItems() 
	{ 
		if (_parts is null) 
		{ 
			return; 
		} 
  
 #if !NET6_0_OR_GREATER 
        List<Uri>? unused = null; 
 #endif 
  
		foreach (var part in _parts) 
		{ 
			if (Package.PartExists(part.Key)) 
			{ 
				part.Value.Part = Package.GetPart(part.Key); 
			} 
			else 
			{ 
 #if NET6_0_OR_GREATER 
				_parts.Remove(part.Key); 
 #else 
				(unused ??= new()).Add(part.Key); 
 #endif 
			} 
// CHANGE START
		} 
 #if !NET6_0_OR_GREATER 
		if (unused is not null) 
		{ 
			foreach (var uri in unused) 
			{ 
				_parts.Remove(uri); 
			} 
		} 
 #endif 
// CHANGE END
	} 
```

**Comment by SirParser** [comment]
@twsouthwick can you have a look?
