### ISSUE TITLE
Deletion of a Part breaks reading other Parts through "using" method

### ISSUE THREAD

**Issue by Asbjoedt** [dotnet/Open-XML-SDK#1729]
**Describe the bug**
Hello
I am upgrading from v2.20 to v.3.0.2.

The new SDK update breaks code which involves deleting/removing some Open XML Parts in my spreadsheet document.

I am applying "using" to read and write the spreadsheet document. I receive error when trying to read any Part after deletion of some other Parts, when I try to read the Part in a new "using" scope. I receive error "Specified part does not exist in the package".

However, some Parts I can remove and it does not result in error e.g. remove SpreadsheetPrinterSettingsPart.

Opening the spreadsheet document wit Excel or LibreOffice works perfectly fine.

Code examples that breaks Open XML SDK ability to read any Part:

```
        // Remove external cell references
        public int Remove_ExternalCellReferences(string filepath)
        {
            int success = 0;

            using (SpreadsheetDocument spreadsheet = SpreadsheetDocument.Open(filepath, true))
            {
                IEnumerable<WorksheetPart> worksheetparts = spreadsheet.WorkbookPart.WorksheetParts;
                foreach (WorksheetPart part in worksheetparts)
                {
                    Worksheet worksheet = part.Worksheet;
                    IEnumerable<Row> rows = worksheet.GetFirstChild<SheetData>().Elements<Row>(); // Find all rows
                    foreach (Row row in rows)
                    {
                        IEnumerable<Cell> cells = row.Elements<Cell>();
                        foreach (Cell cell in cells)
                        {
                            if (cell.CellFormula != null)
                            {
                                string formula = cell.CellFormula.InnerText;
                                if (formula.Length > 1)
                                {
                                    string hit = formula.Substring(0, 1); // Transfer first 1 characters to string
                                    string hit2 = formula.Substring(0, 2); // Transfer first 2 characters to string
                                    if (hit == "[" || hit2 == "'[")
                                    {
                                        CellValue cellvalue = cell.CellValue; // Save current cell value
                                        cell.CellFormula = null;
                                        // If cellvalue does not have a real value
                                        if (cellvalue.Text == "#N/A")
                                        {
                                            cell.DataType = CellValues.String;
                                            cell.CellValue = new CellValue("Invalid data removed");
                                        }
                                        else
                                        {
                                            cell.CellValue = cellvalue; // Insert saved cell value
                                        }
                                        // Add to success
                                        success++;
                                    }
                                }
                            }
                        }
                    }
                }

                // Delete external book references
                List<ExternalWorkbookPart> extwbParts = spreadsheet.WorkbookPart.ExternalWorkbookParts.ToList();
                if (extwbParts.Count > 0)
                {
                    foreach (ExternalWorkbookPart extpart in extwbParts)
                    {
                        var elements = extpart.ExternalLink.ChildElements.ToList();
                        foreach (var element in elements)
                        {
                            if (element.LocalName == "externalBook")
                                spreadsheet.WorkbookPart.DeletePart(extpart);
                        }
                    }
                }

                // Delete calculation chain
                CalculationChainPart calc = spreadsheet.WorkbookPart.CalculationChainPart;
                spreadsheet.WorkbookPart.DeletePart(calc);

                // Delete defined names that includes external cell references
                DefinedNames definedNames = spreadsheet.WorkbookPart.Workbook.DefinedNames;
                if (definedNames != null)
                {
                    var definedNamesList = definedNames.ToList();
                    foreach (DefinedName definedName in definedNamesList)
                    {
                        if (definedName.InnerXml.StartsWith("["))
                            definedName.Remove();
                    }
                }
            }
            return success;
        }
```

```
// Remove data connections
public int Remove_DataConnections(string filepath)
{
    int success = 0;

    using (SpreadsheetDocument spreadsheet = SpreadsheetDocument.Open(filepath, true))
    {
        ConnectionsPart conn = spreadsheet.WorkbookPart.ConnectionsPart;

        // Count connections
        success = conn.Connections.Count();

        // Delete all connections
        spreadsheet.WorkbookPart.DeletePart(conn);
        
        // Delete all QueryTableParts
        IEnumerable<WorksheetPart> worksheetParts = spreadsheet.WorkbookPart.WorksheetParts;
        foreach (WorksheetPart worksheetPart in worksheetParts)
        {
            // Delete all QueryTableParts in WorksheetParts
            List<QueryTablePart> queryTables = worksheetPart.QueryTableParts.ToList(); // Must be a list
            foreach (QueryTablePart queryTablePart in queryTables)
            {
                worksheetPart.DeletePart(queryTablePart);
            }

            // Delete all QueryTableParts, if they are not registered in a WorksheetPart
            List<TableDefinitionPart> tableDefinitionParts = worksheetPart.TableDefinitionParts.ToList();
            foreach (TableDefinitionPart tableDefinitionPart in tableDefinitionParts)
            {
                List<IdPartPair> idPartPairs = tableDefinitionPart.Parts.ToList();
                foreach (IdPartPair idPartPair in idPartPairs)
                {
                    if (idPartPair.OpenXmlPart.ToString() == "DocumentFormat.OpenXml.Packaging.QueryTablePart")
                    {
                        // Delete QueryTablePart
                        tableDefinitionPart.DeletePart(idPartPair.OpenXmlPart);
                        // The TableDefinitionPart must also be deleted
                        worksheetPart.DeletePart(tableDefinitionPart);
                        // And the reference to the TableDefinitionPart in the WorksheetPart must be deleted
                        List<TablePart> tableParts = worksheetPart.Worksheet.Descendants<TablePart>().ToList();
                        foreach (TablePart tablePart in tableParts)
                        {
                            if (idPartPair.RelationshipId == tablePart.Id)
                                tablePart.Remove();
                        }
                    }
                }
            }
        }

        // If spreadsheet contains a CustomXmlMappingsPart, delete databinding
        if (spreadsheet.WorkbookPart.CustomXmlMappingsPart != null)
        {
            CustomXmlMappingsPart xmlMap = spreadsheet.WorkbookPart.CustomXmlMappingsPart;
            List<Map> maps = xmlMap.MapInfo.Elements<Map>().ToList(); // Must be a list
            foreach (Map map in maps)
            {
                if (map.DataBinding != null)
                    map.DataBinding.Remove();
            }
        }
    }
    return success;
}
```

**Observed behavior**
Open XML SDK perceives the spreadsheet document to be broken with error "Specified part does not exist in the package" whenever I try to read any Part, if some Parts have previously been deleted/removed with the "using" method. Excel renders the spreadsheet document without errors.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Office version: Office Professional 2019
 - .NET Target: 
 - DocumentFormat.OpenXml Version: 3.0.2

**Comment by mikeebowen** [comment]
Hi @Asbjoedt, could you be more specific about which parts you mean:

>I am applying "using" to read and write the spreadsheet document. I receive error when trying to read any Part after deletion of some other Parts, when I try to read the Part in a new "using" scope. I receive error "Specified part does not exist in the package".

 When you day "read any Part after deletion of some other Parts", do you mean when you read any Part at all even the WorkbookPart? And which parts do you mean by "deletion of some other Parts"?

**Comment by Asbjoedt** [comment]
When I delete these parts, I get "Specified part does not exist in the package", whenever I try to read *any* Part again:
* ImagePart
* ExternalWorkbookPart
* CalculationChainPart
* ConnectionsPart
* TableDefinitionPart
* SpreadsheetPrinterSettingsPart
* VolatileDependenciesPart

**Comment by twsouthwick** [comment]
please supply a repro so that we can try it out

**Comment by Asbjoedt** [comment]
Hi @mikeebowen, @twsouthwick 
Have you been able to look any further at the issue? 
Can I help to progress issue resolution?

**Comment by mikeebowen** [comment]
Hi @Asbjoedt, I tested your code with the file you linked, but that file does not contain any `HyperLinkRelationships`, so 
```csharp
 List<HyperlinkRelationship> hyperlinks = spreadsheet.GetAllParts().SelectMany(p => p.HyperlinkRelationships).ToList();
```
produces an empty list. It does create the .txt file without error. We have had a few releases, since this issue, so can you update to the latest version of the SDK and try your code again. If it still causes an error, please link the file in question and I'll investigate more.

**Comment by Asbjoedt** [comment]
Hi @mikeebowen 
You are right. There is no hyperlinks. Replace the hyperlink code with the one below, the error should appear on this line.

``
BookViews bookViews = spreadsheet.WorkbookPart.Workbook.GetFirstChild<BookViews>();
``

Here is the full code sample the excerpt is from.

``
// Make first sheet active sheet
public bool Activate_FirstSheet(string filepath)
{
    bool success = false;

    using (SpreadsheetDocument spreadsheet = SpreadsheetDocument.Open(filepath, true))
    {
        BookViews bookViews = spreadsheet.WorkbookPart.Workbook.GetFirstChild<BookViews>();
        WorkbookView workbookView = bookViews.GetFirstChild<WorkbookView>();
        if (workbookView.ActiveTab != null)
        {
            var activeSheetId = workbookView.ActiveTab.Value;
            if (activeSheetId > 0)
            {
                // Set value in workbook.xml to first sheet
                workbookView.ActiveTab.Value = 0;

                // Iterate all worksheets to detect if sheetview.Tabselected exists and change it
                IEnumerable<WorksheetPart> worksheets = spreadsheet.WorkbookPart.WorksheetParts;
                foreach (WorksheetPart worksheet in worksheets)
                {
                    SheetViews sheetviews = worksheet.Worksheet.SheetViews;
                    foreach (SheetView sheetview in sheetviews)
                    {
                        sheetview.TabSelected = null;
                    }
                }
                success = true;
            }
        }
    }
    return success;
}
``

The call stack log is this; see below. I notice there is something about malformed URI.

``
System.InvalidOperationException
  HResult=0x80131509
  Message=Specified part does not exist in the package.
  Source=System.IO.Packaging
  StackTrace:
   at System.IO.Packaging.Package.GetPart(Uri partUri)
   at DocumentFormat.OpenXml.Features.PackageFeatureBase.DocumentFormat.OpenXml.Packaging.IPackage.GetPart(Uri uriTarget)
   at DocumentFormat.OpenXml.Packaging.PackageUriHandlingExtensions.MalformedUriHandlingPackage.GetPart(Uri uriTarget)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id)
   at DocumentFormat.OpenXml.Packaging.PartRelationshipsFeature.LoadReferencedPartsAndRelationships()
   at DocumentFormat.OpenXml.Packaging.PartRelationshipsFeature.DocumentFormat.OpenXml.Features.IPartRelationshipsFeature.get_Count()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.LoadAllParts()
   at DocumentFormat.OpenXml.Features.StrictNamespaceExtensions.StrictNamespaceFeature.DocumentFormat.OpenXml.Features.IStrictNamespaceFeature.get_Found()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.LoadDomTree[T]()
   at DocumentFormat.OpenXml.Packaging.WorkbookPart.get_Workbook()
   at CLISC.Archive_Requirements.Activate_FirstSheet(String filepath) in C:\Users\asbjoedt\source\repos\Asbjoedt\CLISC\CLISC\Archive_Requirements_Change.cs:line 410
   at CLISC.Archive_Requirements.Change_XLSX_Requirements(List`1 arcReq, String filepath, Boolean fullcompliance) in C:\Users\asbjoedt\source\repos\Asbjoedt\CLISC\CLISC\Archive_Requirements_Change.cs:line 80
   at CLISC.Archive.Archive_Spreadsheets(String Results_Directory, List`1 File_List, Boolean fullcompliance) in C:\Users\asbjoedt\source\repos\Asbjoedt\CLISC\CLISC\Archive.cs:line 95
   at CLISC.Program_Real.Execute(String function, String inputdir, String outputdir, Boolean recurse, Boolean fullcompliance) in C:\Users\asbjoedt\source\repos\Asbjoedt\CLISC\CLISC\Program_Real.cs:line 57
   at CLISC.Program.Run(Program_Args Arg) in C:\Users\asbjoedt\source\repos\Asbjoedt\CLISC\CLISC\Program.cs:line 56
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at CLISC.Program.Main(String[] args) in C:\Users\asbjoedt\source\repos\Asbjoedt\CLISC\CLISC\Program.cs:line 21

``

I just made a branch of my code, upgraded to latest v3 and still get the error in my codebase across multiple different test files with different content. The common denominator seem to be that I have removed a "Part" using the SDK.

``
System.InvalidOperationException: 'Specified part does not exist in the package.'
``

**Comment by mikeebowen** [comment]
Hi @Asbjoedt, Thanks for updating and trying it again. Unfortunately, I copied your code, and it runs without errors for me with the .xlsx you provided. The stack trace you provided looks like it is calling several other methods besides the one provided:

```
C:\Users\asbjoedt\source\repos\Asbjoedt\CLISC\CLISC\Archive_Requirements_Change.cs:line 410
   at CLISC.Archive_Requirements.Change_XLSX_Requirements(List`1 arcReq, String filepath, Boolean fullcompliance) in C:\Users\asbjoedt\source\repos\Asbjoedt\CLISC\CLISC\Archive_Requirements_Change.cs:line 80
   at CLISC.Archive.Archive_Spreadsheets(String Results_Directory, List`1 File_List, Boolean fullcompliance) in C:\Users\asbjoedt\source\repos\Asbjoedt\CLISC\CLISC\Archive.cs:line 95
   at CLISC.Program_Real.Execute(String function, String inputdir, String outputdir, Boolean recurse, Boolean fullcompliance) in C:\Users\asbjoedt\source\repos\Asbjoedt\CLISC\CLISC\Program_Real.cs:line 57
   at CLISC.Program.Run(Program_Args Arg) in C:\Users\asbjoedt\source\repos\Asbjoedt\CLISC\CLISC\Program.cs:line 56
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at CLISC.Program.Main(String[] args) in C:\Users\asbjoedt\source\repos\Asbjoedt\CLISC\CLISC\Program.cs:line 21
```

Is it possible to link to the whole project? I think the issue might be somewhere outside of the methods you provided.

**Comment by mikeebowen** [comment]
Hi @Asbjoedt, 
 
Part of the problem is that you need to use the [Null-conditional operators](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators) `?` to prevent trying to access properties on a null object change your condition to 

```csharp
if (spreadsheet.WorkbookPart?.Workbook?.WorkbookProtection != null || spreadsheet.WorkbookPart?.Workbook?.FileSharing != null)
```

Looking in your project, you have the same issue in multiple places. I see that your are using .net 6.0, which is out of support. If you update your project to .Net 8 then these issues will show as warnings in Visual Studio. For more about these type of errors please see [Resolve nullable warnings](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings?f1url=%3FappId%3Droslyn%26k%3Dk(CS8602)).

There are a few other issues that can be resolved by using the [?? and ??= operators - the null-coalescing operators](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator).

I resolved the nullable reference issues in [my fork of your project(https://github.com/Asbjoedt/CLISC/compare/oxmlsdk-v3-upgrade-new-try...mikeebowen:CLISC:oxmlsdk-v3-upgrade-new-try).

The other issue that is causing the 'Specified part does not exist in the package.' error is that when the SDK reads the rels file and tries to open a part that is listed as a relationship, but has been removed from the package. I'm still looking into that.

Could you explain more what your trying to do with this project?

**Comment by Asbjoedt** [comment]
So forget about this long text above, did you manage to debug further the issues to why migrating from Open XML SDK v2.2 to v3 breaks my codebase as per your reply:

> The other issue that is causing the 'Specified part does not exist in the package.' error is that when the SDK reads the rels file and tries to open a part that is listed as a relationship, but has been removed from the package. I'm still looking into that.

?

Thank you.
