### ISSUE TITLE
System.IO.IOException: Stream was too long error on .NET Core 2.0 application

### ISSUE THREAD

**Issue by AntoineLarine** [dotnet/Open-XML-SDK#244]
In .NET Core 2 console application ([ConsoleApp1.zip](https://github.com/OfficeDev/Open-XML-SDK/files/1309342/ConsoleApp1.zip)) writing a large Excel file stops with the following error:
System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.WrappedStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   at System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteAttributesTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlPartWriter.WriteElement(OpenXmlElement elementObject)
   at ConsoleApp1.Program.WriteRandomValuesSAX(String fileName, String sheetName) in C:\Users\anton\Documents\Visual Studio 2017\Projects\ConsoleApplication2\ConsoleApp1\Program.cs:line 80
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\anton\Documents\Visual Studio 2017\Projects\ConsoleApplication2\ConsoleApp1\Program.cs:line 105

And application workset size was growed up to 4 GiB. But there is a x64 application, so the process memory is not limited by 4GiB

Meanwhile in .NET FW4.7 same application ([ConsoleApp2.zip](https://github.com/OfficeDev/Open-XML-SDK/files/1309348/ConsoleApp2.zip)) works perfectly with 10 MB workset size

**Comment by twsouthwick** [comment]
There appears to be a memory leak here in the .NET Standard version of the library.

**Comment by twsouthwick** [comment]
I was able to repro this issue outside of the DocumentFormat.OpenXML SDK using just the BCL. I've logged an issue at dotnet/corefx to see what the issue is.

**Comment by tarunchopra** [comment]
Thanks @twsouthwick; appreciate your help.

**Comment by igorko** [comment]
Voting for this to be fixed.

**Comment by BNarayanSharma** [comment]
Is there any update on when it will be fixed? Due to this issue, my .NET Core Migration for a few projects has been on hold for the last two years.

I need to generate a large excel file, and it throws the exception "Stream was too long"

I have tried with .NET Core 7.0 as well and still failing. I do not understand why it has been marked as fixed.
If I run with .NET Framework 4.x.x it works perfectly fine but always fails with .NET Core 3.1, .NET 5, .NET 6 & .NET 7

**Comment by martinokello** [comment]
This to me is obviously wrong, as it gives me nightmares, not disposing the memory stream. How else should one do it without saving the file to disk, but in memory manipulation. Beats me.

**Comment by martinokello** [comment]
And I get an error message: Stream was too long when sending the email.

**Comment by BogdanGrytsko** [comment]
Any updates on the issue? Getting it also, .NET 6

**Comment by twsouthwick** [comment]
This is something that needs to go into .NET itself - I've tried multiple ways to shim it at our layer and have not been able to get around it. Please add comments to https://github.com/dotnet/runtime/issues/1544 to get visibility there.

**Comment by AntoineLarine** [comment]
I've checked this bug on .NET 7. Unfortunately, the problem hasn't been fixed yet.

**Comment by AlfredHellstern** [comment]
See also:
- #244

**Comment by udlose** [comment]
Is there any update on this bug?

**Comment by mikeebowen** [comment]
> Is there any update on this bug?

Unfortunately, there's no fix in the dotnet runtime yet.

**Comment by udlose** [comment]
This is kinda important to get this fixed and it needs to be driven by the fix in the .NET Runtime.

EVERYONE, please make sure to vote for this item and make some noise on that issue so we can get it moving along with some sense of urgency for the runtime team.  It's disappointing that something so egregious has lingered without a resolution for so many years...

**_Please add comments to https://github.com/dotnet/runtime/issues/1544 to get visibility there._**

**Comment by mdzieg** [comment]
Ok, so I ended up with my own workaround. I implemented folder-based System.IO.Package implementation and substitute this on Spreadsheet opening.
It works just fine.
The fact that I have to do this on a 64-bit operating system because of 2GB memory limitation of MemoryStream is annoying.
In addition to that, the problem seems to be reported in 2017... which is 7 years ago. This makes 'annoying' an understatement.

**Comment by ahdata** [comment]
> Ok, so I ended up with my own workaround. I implemented folder-based System.IO.Package implementation and substitute this on Spreadsheet opening. It works just fine. The fact that I have to do this on a 64-bit operating system because of 2GB memory limitation of MemoryStream is annoying. In addition to that, the problem seems to be reported in 2017... which is 7 years ago. This makes 'annoying' an understatement.

@mdzieg would you have any example code to share?
